import os
import time
from typing import Any

import numpy as np
import pyttsx3
import scipy.io.wavfile
import streamlit as st
from dotenv import find_dotenv, load_dotenv

from langchain.chains import LLMChain
from langchain.chat_models import ChatOpenAI
from langchain.prompts import PromptTemplate

from transformers import pipeline

from utils.custom import css_code


# ============================================================
# LOAD ENVIRONMENT VARIABLES
# ============================================================

load_dotenv(find_dotenv())

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")


# ============================================================
# PROGRESS BAR
# ============================================================

def progress_bar(amount_of_time: int) -> Any:
    """
    Display a simple progress bar.
    """

    progress_text = "Please wait, Generative models hard at work"

    my_bar = st.progress(
        0,
        text=progress_text
    )

    for percent_complete in range(amount_of_time):
        time.sleep(0.04)

        my_bar.progress(
            percent_complete + 1,
            text=progress_text
        )

    time.sleep(1)
    my_bar.empty()


# ============================================================
# IMAGE TO TEXT
# ============================================================

@st.cache_resource
def load_image_caption_model():
    """
    Load the BLIP image captioning model only once.
    """

    return pipeline(
        "image-to-text",
        model="Salesforce/blip-image-captioning-base"
    )


def generate_text_from_image(url: str) -> str:
    """
    Generate a description of the uploaded image.
    """

    image_to_text = load_image_caption_model()

    result = image_to_text(url)

    generated_text = result[0]["generated_text"]

    print(f"IMAGE INPUT: {url}")
    print(f"GENERATED TEXT OUTPUT: {generated_text}")

    return generated_text


# ============================================================
# TEXT TO STORY
# ============================================================

def generate_story_from_text(scenario: str) -> str:
    """
    Generate a short story from the image description using Gemini.
    """

    prompt_template = """
You are a talented storyteller.

Create a short, interesting and meaningful story based on
the following image description.

Rules:
- Maximum 50 words.
- Use simple English.
- Make the story creative.
- Do not mention that the story was generated by AI.

IMAGE DESCRIPTION:
{scenario}

STORY:
"""

    prompt = PromptTemplate(
        template=prompt_template,
        input_variables=["scenario"]
    )

    if not GEMINI_API_KEY:
        raise ValueError(
            "GEMINI_API_KEY is missing. "
            "Please add it to your .env file."
        )

    llm = ChatOpenAI(
        model_name="gemini-3.5-flash-lite",
        temperature=0.9,
        openai_api_key=GEMINI_API_KEY,
        openai_api_base=(
            "https://generativelanguage.googleapis.com/v1beta/openai/"
        ),
    )

    story_llm = LLMChain(
        llm=llm,
        prompt=prompt,
        verbose=True
    )

    generated_story = story_llm.predict(
        scenario=scenario
    )

    generated_story = generated_story.strip()

    print(f"TEXT INPUT: {scenario}")
    print(f"GENERATED STORY OUTPUT: {generated_story}")

    return generated_story


# ============================================================
# LOAD FEMALE TEXT TO SPEECH VOICE
# ============================================================

@st.cache_resource
def load_tts_engine():
    """
    Load a Windows offline female voice.
    """

    engine = pyttsx3.init()
    voices = engine.getProperty("voices")
    female_voice = next(
        (
            voice for voice in voices
            if any(
                name in f"{voice.name} {voice.id}".lower()
                for name in ("female", "zira", "hazel", "susan", "heera")
            )
        ),
        voices[0],
    )
    engine.setProperty("voice", female_voice.id)
    engine.setProperty("rate", 165)
    engine.setProperty("volume", 1.0)
    return engine


# ============================================================
# TEXT TO SPEECH
# ============================================================

def generate_speech_from_text(message: str) -> str | None:
    """
    Convert the generated story into speech.

    The speech is generated locally using a female Windows voice.
    """

    try:
        if not message or not message.strip():
            st.error("No story text was generated.")
            return None

        print("TEXT TO SPEECH INPUT:")
        print(message)

        output_file = "generated_audio.wav"
        tts = load_tts_engine()
        tts.save_to_file(message.strip(), output_file)
        tts.runAndWait()

        print(
            f"Speech generated successfully: {output_file}"
        )

        return output_file

    except Exception as error:
        print("TTS ERROR:", error)

        st.error(
            f"Unable to generate speech: {error}"
        )

        return None


# ============================================================
# MAIN APPLICATION
# ============================================================

def main() -> None:
    """
    Main Streamlit application.
    """

    st.set_page_config(
        page_title="IMAGE TO STORY CONVERTER",
        page_icon="🖼️",
        layout="centered"
    )

    # Custom CSS
    st.markdown(
        css_code,
        unsafe_allow_html=True
    )

    with st.sidebar:
        logo_path = (
            "C:/Users/sadia/.codex/generated_images/"
            "01a0c279-1310-7940-9b49-d50fcb6f2711/"
            "exec-661cc922-ee27-4c0c-b029-e491b70992b3.png"
        )
        st.image(logo_path, width=100)
        st.caption("Created by Mohammed Sadia")

    # Page title
    st.header("🖼️ Image-to-Story Converter")

    st.write(
        "Upload an image and let AI describe it, "
        "create a story, and convert the story into speech."
    )

    # ========================================================
    # FILE UPLOAD
    # ========================================================

    uploaded_file = st.file_uploader(
        "Please choose a file to upload",
        type=["jpg", "jpeg", "png"]
    )

    if uploaded_file is not None:

        print(uploaded_file)

        # Save uploaded image
        bytes_data = uploaded_file.getvalue()

        with open(
            uploaded_file.name,
            "wb"
        ) as file:
            file.write(bytes_data)

        # Display image
        st.image(
            uploaded_file,
            caption="Uploaded Image",
            width="stretch"
        )

        # ====================================================
        # STEP 1 - IMAGE TO TEXT
        # ====================================================

        with st.spinner(
            "🔍 Analyzing the image..."
        ):
            scenario = generate_text_from_image(
                uploaded_file.name
            )

        # ====================================================
        # STEP 2 - TEXT TO STORY
        # ====================================================

        with st.spinner(
            "✍️ Creating your story..."
        ):
            story = generate_story_from_text(
                scenario
            )

        # ====================================================
        # STEP 3 - STORY TO SPEECH
        # ====================================================

        with st.spinner(
            "🔊 Converting story to speech..."
        ):
            audio_file = generate_speech_from_text(
                story
            )

        # ====================================================
        # DISPLAY IMAGE SCENARIO
        # ====================================================

        with st.expander(
            "🔍 Generated Image Scenario"
        ):
            st.write(scenario)

        # ====================================================
        # DISPLAY STORY
        # ====================================================

        with st.expander(
            "📖 Generated Short Story"
        ):
            st.write(story)

        # ====================================================
        # DISPLAY AUDIO
        # ====================================================

        if audio_file is not None:

            st.subheader(
                "🔊 Generated Speech"
            )

            st.audio(
                audio_file
            )

            st.success(
                "✅ Image → Story → Speech completed successfully!"
            )

        else:

            st.warning(
                "⚠️ Story was generated, "
                "but speech generation failed."
            )


# ============================================================
# RUN APPLICATION
# ============================================================

if __name__ == "__main__":
    main()
